server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://Patient-Service:4000/
              predicates:
                - Path=/api/patient/**
              filters:
                - StripPrefix=1
              # Rest Client -> http://localhost:4004/api/patient/get -> forwarded to http://Patient-Service:4000/get

            - id: api-docs-patient-route
              uri: http://Patient-Service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs
              # Swagger -> http://localhost:4004/api-docs/patients -> rewritten to /v3/api-docs
