server:
  port: 4004  #Api_Gateway port Listen on 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

 #Client Request to Api Gateway -> localhost:4004/auth/login  then goes forward to  localhost:4005/login
            - id: patient-service-route
              uri: http://Auth-Service:4005/
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: patient-service-route
              uri: http://Patient-Service:4000/
              predicates:
                - Path=/api/patient/**
              filters:
                - StripPrefix=1
              # Rest Client -> http://localhost:4004/api/patient/get -> forwarded to http://Patient-Service:4000/get

            - id: api-docs-patient-route
              uri: http://Patient-Service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs
              # Swagger -> http://localhost:4004/api-docs/patients -> rewritten to /v3/api-docs
