###  Create request to Patient
POST http://localhost:4004/api/patient/createpatient
Content-Type: application/json

{
  "name": "M Ali",
  "email": "MAlikhan@gmail.com",
  "address": "123 Street DHA, Lahore",
  "phone": "03001234523",
  "dateOfBirth": "2008-05-15",
  "registeredDate": "2024-05-07"
}


###