###  Create request to Patient
POST http://localhost:4000/patient/createpatient
Content-Type: application/json

{
  "name": "John Duo",
  "email": "john@4663335gmail.com",
  "address": "123 Street, Lahore",
  "phone": "03001234567",
  "dateOfBirth": "1995-06-15",
  "registeredDate": "2025-05-09"
}


###